// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// MANUAL CONFIGURATION TEMPLATE
/// Replace the values below with your Firebase project configuration.
/// You can get these values from:
/// Firebase Console > Project Settings > General > Your apps > Web app config
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjgyveaxiPcuxkqtp5UryvBa1PXb5fo98',
    appId: '1:480601990521:web:4b6f324e0d06a3974ffba8',
    messagingSenderId: '480601990521',
    projectId: 'mad-inclass14-ashir',
    authDomain: 'mad-inclass14-ashir.firebaseapp.com',
    storageBucket: 'mad-inclass14-ashir.firebasestorage.app',
    measurementId: 'G-HR313N3QVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCjAIaJl0OIjdq1xoaLyVCxqVTtTj49kw',
    appId: '1:480601990521:android:0a952215242523ac4ffba8',
    messagingSenderId: '480601990521',
    projectId: 'mad-inclass14-ashir',
    storageBucket: 'mad-inclass14-ashir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_09VuA3Atq9XKMbauJRzxdjJKhZQwZMo',
    appId: '1:480601990521:ios:3248b122099ad7e24ffba8',
    messagingSenderId: '480601990521',
    projectId: 'mad-inclass14-ashir',
    storageBucket: 'mad-inclass14-ashir.firebasestorage.app',
    iosBundleId: 'com.example.madInclass14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_09VuA3Atq9XKMbauJRzxdjJKhZQwZMo',
    appId: '1:480601990521:ios:3248b122099ad7e24ffba8',
    messagingSenderId: '480601990521',
    projectId: 'mad-inclass14-ashir',
    storageBucket: 'mad-inclass14-ashir.firebasestorage.app',
    iosBundleId: 'com.example.madInclass14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjgyveaxiPcuxkqtp5UryvBa1PXb5fo98',
    appId: '1:480601990521:web:4b6f324e0d06a3974ffba8',
    messagingSenderId: '480601990521',
    projectId: 'mad-inclass14-ashir',
    authDomain: 'mad-inclass14-ashir.firebaseapp.com',
    storageBucket: 'mad-inclass14-ashir.firebasestorage.app',
    measurementId: 'G-HR313N3QVK',
  );

}